"""
Verification Module for SecureStego Platform Signature System

Purpose:
This module provides platform signature verification capabilities to ensure
that only media generated by SecureStego can be extracted.

Responsibilities:
- Generate cryptographic platform signatures
- Validate platform signatures during extraction
- Provide unified verification interface for all media types
- Handle verification failures gracefully

Workflow:
1. During embedding: Generate and inject platform signature
2. During extraction: Verify platform signature before proceeding
3. If verification fails: Reject file and stop extraction

Security Considerations:
- Uses HMAC-SHA256 for cryptographic verification
- Platform secret key stored in environment variables
- Verification happens only on backend
- Never exposes secrets to frontend
"""

from app.verification.platform_signature import platform_signature
from app.verification.signature_validator import signature_validator
from app.verification.signature_constants import (
    PLATFORM_NAME,
    PLATFORM_VERSION,
    SUPPORTED_MEDIA_TYPES,
    SIGNATURE_VERSION
)
from app.verification.signature_exceptions import (
    SignatureVerificationError,
    InvalidSignatureError,
    MissingSignatureError,
    TamperedSignatureError,
    VersionMismatchError
)

__all__ = [
    'platform_signature',
    'signature_validator',
    'PLATFORM_NAME',
    'PLATFORM_VERSION',
    'SUPPORTED_MEDIA_TYPES',
    'SIGNATURE_VERSION',
    'SignatureVerificationError',
    'InvalidSignatureError',
    'MissingSignatureError',
    'TamperedSignatureError',
    'VersionMismatchError'
]
