"""
Platform Signature Module for SecureStego Platform Verification

Purpose:
This module handles the generation of platform signatures for media files.
Platform signatures are cryptographic proofs that media was generated by
SecureStego platform.

Responsibilities:
- Generate platform signature structures
- Create HMAC-SHA256 signatures
- Serialize signatures to binary format
- Include platform metadata in signatures

Workflow:
1. Create signature structure with platform metadata
2. Generate HMAC-SHA256 using platform secret key
3. Serialize signature to binary for embedding
4. Return signature ready for steganography embedding

Security Considerations:
- Uses HMAC-SHA256 for cryptographic verification
- Platform secret key loaded from environment variables
- Signature includes timestamp for audit trail
- Signature includes media type for replay protection
- Never exposes secret key in signature
"""

import json
import hmac
import hashlib
import base64
from datetime import datetime
from typing import Dict, Any
from app.utils.logging_config import get_logger
from app.verification.signature_constants import (
    PLATFORM_NAME,
    PLATFORM_VERSION,
    SIGNATURE_VERSION,
    SIGNATURE_FIELD_PLATFORM,
    SIGNATURE_FIELD_VERSION,
    SIGNATURE_FIELD_SIGNATURE,
    SIGNATURE_FIELD_CREATED_AT,
    SIGNATURE_FIELD_MEDIA_TYPE,
    HMAC_ALGORITHM,
    HMAC_DIGEST_SIZE
)
from app.config import settings

logger = get_logger(__name__)


class PlatformSignature:
    """
    Handles platform signature generation for SecureStego.
    
    Why this exists:
    - Provides a centralized signature generation interface
    - Ensures consistent signature format across all media types
    - Implements cryptographic verification using HMAC-SHA256
    - Enables platform verification during extraction
    
    Security Considerations:
    - Platform secret key loaded from environment variables
    - HMAC-SHA256 provides cryptographic integrity
    - Timestamp prevents replay attacks
    - Media type prevents cross-media signature reuse
    - Secret key never exposed in signature or logs
    """
    
    def __init__(self):
        """
        Initialize the platform signature generator.
        
        Loads platform secret key from environment variables.
        """
        self.platform_name = PLATFORM_NAME
        self.platform_version = PLATFORM_VERSION
        self.signature_version = SIGNATURE_VERSION
        
        # Load platform secret key from environment
        # This key is used for HMAC generation
        self.platform_secret_key = getattr(settings, 'platform_secret_key', None)
        
        if not self.platform_secret_key:
            logger.warning(
                "PLATFORM_SECRET_KEY not set in environment. "
                "Signature verification will fail."
            )
        else:
            logger.info("PlatformSignature initialized with secret key")
    
    def generate_signature(
        self,
        media_type: str,
        payload_data: bytes = None
    ) -> Dict[str, Any]:
        """
        Generate a platform signature structure.
        
        This method:
        1. Creates signature structure with platform metadata
        2. Generates HMAC-SHA256 using platform secret key
        3. Includes timestamp for audit trail
        4. Includes media type for replay protection
        5. Returns signature dictionary
        
        Parameters:
        media_type (str):
            Type of media (image, video, audio, document).
        payload_data (bytes, optional):
            Optional payload data to include in HMAC generation.
            If provided, HMAC covers both metadata and payload.
            This binds the signature to the specific payload.
            
        Returns:
        Dict[str, Any]: Signature dictionary containing:
            - platform: Platform name (SecureStego)
            - version: Platform version
            - signature: HMAC-SHA256 signature (base64 encoded)
            - createdAt: ISO-8601 timestamp
            - mediaType: Media type
            
        Raises:
        ValueError: If platform secret key is not configured.
        """
        try:
            logger.info(f"Generating platform signature for media type: {media_type}")
            
            # Check if platform secret key is configured
            if not self.platform_secret_key:
                raise ValueError(
                    "PLATFORM_SECRET_KEY not configured. "
                    "Cannot generate platform signature."
                )
            
            # Create timestamp
            created_at = datetime.utcnow().isoformat() + "Z"
            
            # Create data to sign
            # We sign: platform + version + mediaType + createdAt + (optional payload)
            data_to_sign = {
                "platform": self.platform_name,
                "version": self.platform_version,
                "mediaType": media_type,
                "createdAt": created_at
            }
            
            # If payload data is provided, include it in HMAC
            # This binds the signature to the specific payload
            if payload_data:
                # Hash the payload to include in signature
                payload_hash = hashlib.sha256(payload_data).hexdigest()
                data_to_sign["payloadHash"] = payload_hash
            
            # Convert to string for HMAC
            data_string = json.dumps(data_to_sign, separators=(',', ':'), sort_keys=True)
            
            # Generate HMAC-SHA256
            # The secret key is used as the HMAC key
            signature_bytes = hmac.new(
                self.platform_secret_key.encode('utf-8'),
                data_string.encode('utf-8'),
                hashlib.sha256
            ).digest()
            
            # Encode signature to base64 for JSON serialization
            signature_b64 = base64.b64encode(signature_bytes).decode('utf-8')
            
            # Create signature structure
            signature_dict = {
                SIGNATURE_FIELD_PLATFORM: self.platform_name,
                SIGNATURE_FIELD_VERSION: self.signature_version,
                SIGNATURE_FIELD_SIGNATURE: signature_b64,
                SIGNATURE_FIELD_CREATED_AT: created_at,
                SIGNATURE_FIELD_MEDIA_TYPE: media_type
            }
            
            logger.info(
                f"Platform signature generated: "
                f"platform={self.platform_name}, "
                f"version={self.signature_version}, "
                f"mediaType={media_type}"
            )
            
            return signature_dict
            
        except Exception as e:
            logger.error(f"Platform signature generation error: {e}")
            raise
    
    def serialize_signature(self, signature_dict: Dict[str, Any]) -> bytes:
        """
        Serialize the signature dictionary to binary format.
        
        This method:
        1. Converts signature dictionary to JSON string
        2. Encodes JSON string to UTF-8 bytes
        3. Returns binary data ready for embedding
        
        Parameters:
        signature_dict (Dict[str, Any]):
            Signature dictionary from generate_signature().
            
        Returns:
        bytes: Binary representation of signature.
            
        Raises:
        ValueError: If signature cannot be serialized.
        """
        try:
            logger.info("Serializing platform signature to binary")
            
            # Convert to JSON string
            # Use compact JSON to minimize size
            json_string = json.dumps(signature_dict, separators=(',', ':'))
            
            # Encode to UTF-8 bytes
            binary_data = json_string.encode('utf-8')
            
            logger.info(f"Platform signature serialized: {len(binary_data)} bytes")
            
            return binary_data
            
        except Exception as e:
            logger.error(f"Platform signature serialization error: {e}")
            raise ValueError(f"Failed to serialize platform signature: {e}")
    
    def get_signature_size(self, signature_dict: Dict[str, Any]) -> int:
        """
        Calculate the binary size of a signature.
        
        Parameters:
        signature_dict (Dict[str, Any]):
            Signature dictionary.
            
        Returns:
        int: Size in bytes when serialized.
        """
        binary_data = self.serialize_signature(signature_dict)
        return len(binary_data)
    
    def generate_and_serialize(
        self,
        media_type: str,
        payload_data: bytes = None
    ) -> bytes:
        """
        Convenience method to generate and serialize signature in one call.
        
        This method:
        1. Generates platform signature
        2. Serializes to binary format
        3. Returns binary data ready for embedding
        
        Parameters:
        media_type (str):
            Type of media (image, video, audio, document).
        payload_data (bytes, optional):
            Optional payload data to include in HMAC generation.
            
        Returns:
        bytes: Binary signature ready for embedding.
        """
        signature_dict = self.generate_signature(media_type, payload_data)
        return self.serialize_signature(signature_dict)


# Global platform signature instance
platform_signature = PlatformSignature()
