"""
Signature Validator Module for SecureStego Platform Verification

Purpose:
This module handles the validation of platform signatures from media files.
It verifies that media was generated by SecureStego using cryptographic
HMAC-SHA256 verification.

Responsibilities:
- Extract and parse platform signatures from binary data
- Verify HMAC-SHA256 signatures
- Validate platform identity
- Validate version compatibility
- Validate media type consistency
- Provide detailed verification diagnostics

Workflow:
1. Extract signature binary from media
2. Deserialize signature to dictionary
3. Verify HMAC-SHA256 using platform secret key
4. Validate platform identity matches SecureStego
5. Validate version is supported
6. Validate media type matches actual media
7. Return verification result with diagnostics

Security Considerations:
- Uses HMAC-SHA256 for cryptographic verification
- Platform secret key loaded from environment variables
- Rejects files without valid signature
- Rejects files with tampered signatures
- Rejects files from external platforms
- Logs all verification attempts for audit trail
"""

import json
import hmac
import hashlib
import base64
import time
from typing import Dict, Any, Optional
from app.utils.logging_config import get_logger
from app.verification.signature_constants import (
    PLATFORM_NAME,
    PLATFORM_VERSION,
    SUPPORTED_MEDIA_TYPES,
    SUPPORTED_SIGNATURE_VERSIONS,
    SIGNATURE_FIELD_PLATFORM,
    SIGNATURE_FIELD_VERSION,
    SIGNATURE_FIELD_SIGNATURE,
    SIGNATURE_FIELD_CREATED_AT,
    SIGNATURE_FIELD_MEDIA_TYPE,
    HMAC_ALGORITHM,
    HMAC_DIGEST_SIZE,
    MAX_SIGNATURE_SIZE,
    MIN_SIGNATURE_SIZE,
    DEBUG_SECTION_TITLE
)
from app.verification.signature_exceptions import (
    MissingSignatureError,
    InvalidSignatureError,
    TamperedSignatureError,
    VersionMismatchError,
    PlatformMismatchError,
    MediaTypeMismatchError
)
from app.config import settings

logger = get_logger(__name__)


class SignatureValidator:
    """
    Validates platform signatures for SecureStego.
    
    Why this exists:
    - Provides a centralized signature validation interface
    - Ensures only SecureStego-generated media can be extracted
    - Implements cryptographic verification using HMAC-SHA256
    - Provides detailed diagnostics for debugging
    - Prevents extraction of externally-generated media
    
    Security Considerations:
    - Platform secret key loaded from environment variables
    - HMAC-SHA256 provides cryptographic integrity verification
    - Rejects files without valid signatures
    - Rejects files with tampered signatures
    - Rejects files from external platforms
    - Logs all verification attempts for security monitoring
    """
    
    def __init__(self):
        """
        Initialize the signature validator.
        
        Loads platform secret key from environment variables.
        """
        self.platform_name = PLATFORM_NAME
        self.platform_version = PLATFORM_VERSION
        self.supported_media_types = SUPPORTED_MEDIA_TYPES
        self.supported_signature_versions = SUPPORTED_SIGNATURE_VERSIONS
        
        # Load platform secret key from environment
        # This key is used for HMAC verification
        self.platform_secret_key = getattr(settings, 'platform_secret_key', None)
        
        if not self.platform_secret_key:
            logger.warning(
                "PLATFORM_SECRET_KEY not set in environment. "
                "Signature verification will fail."
            )
        else:
            logger.info("SignatureValidator initialized with secret key")
    
    def deserialize_signature(self, signature_binary: bytes) -> Dict[str, Any]:
        """
        Deserialize binary signature data to dictionary.
        
        This method:
        1. Decodes bytes to UTF-8 string
        2. Parses JSON string to dictionary
        3. Validates signature structure
        4. Returns signature dictionary
        
        Parameters:
        signature_binary (bytes):
            Binary signature data extracted from media.
            
        Returns:
        Dict[str, Any]: Deserialized signature dictionary.
            
        Raises:
        InvalidSignatureError: If signature cannot be deserialized or is invalid.
        """
        try:
            logger.info("Deserializing platform signature from binary")
            logger.info(f"Signature binary size: {len(signature_binary)} bytes")
            
            # Validate signature size
            if len(signature_binary) < MIN_SIGNATURE_SIZE:
                raise InvalidSignatureError(
                    f"Signature too small: {len(signature_binary)} bytes "
                    f"(minimum: {MIN_SIGNATURE_SIZE} bytes)"
                )
            
            if len(signature_binary) > MAX_SIGNATURE_SIZE:
                raise InvalidSignatureError(
                    f"Signature too large: {len(signature_binary)} bytes "
                    f"(maximum: {MAX_SIGNATURE_SIZE} bytes)"
                )
            
            # Decode from UTF-8 bytes
            json_string = signature_binary.decode('utf-8')
            
            # Parse JSON
            signature_dict = json.loads(json_string)
            
            # Validate signature structure
            self._validate_signature_structure(signature_dict)
            
            logger.info("Platform signature deserialized successfully")
            
            return signature_dict
            
        except json.JSONDecodeError as e:
            logger.error(f"JSON decode error: {e}")
            raise InvalidSignatureError(f"Invalid signature format: not valid JSON")
        except UnicodeDecodeError as e:
            logger.error(f"Unicode decode error: {e}")
            raise InvalidSignatureError(f"Invalid signature format: not valid UTF-8")
        except Exception as e:
            logger.error(f"Signature deserialization error: {e}")
            raise InvalidSignatureError(f"Failed to deserialize signature: {e}")
    
    def _validate_signature_structure(self, signature_dict: Dict[str, Any]) -> None:
        """
        Validate the structure of a deserialized signature.
        
        This ensures all required fields are present and have correct types.
        
        Parameters:
        signature_dict (Dict[str, Any]):
            Signature dictionary to validate.
            
        Raises:
        InvalidSignatureError: If signature is missing required fields or has invalid types.
        """
        required_fields = {
            SIGNATURE_FIELD_PLATFORM: str,
            SIGNATURE_FIELD_VERSION: str,
            SIGNATURE_FIELD_SIGNATURE: str,
            SIGNATURE_FIELD_CREATED_AT: str,
            SIGNATURE_FIELD_MEDIA_TYPE: str
        }
        
        for field, expected_type in required_fields.items():
            if field not in signature_dict:
                raise InvalidSignatureError(
                    f"Invalid signature: missing required field '{field}'"
                )
            
            if not isinstance(signature_dict[field], expected_type):
                raise InvalidSignatureError(
                    f"Invalid signature: field '{field}' must be {expected_type.__name__}, "
                    f"got {type(signature_dict[field]).__name__}"
                )
        
        logger.info("Signature structure validation passed")
    
    def verify_signature(
        self,
        signature_dict: Dict[str, Any],
        actual_media_type: str,
        payload_data: bytes = None
    ) -> Dict[str, Any]:
        """
        Verify a platform signature using HMAC-SHA256.
        
        This method:
        1. Verifies HMAC-SHA256 using platform secret key
        2. Validates platform identity matches SecureStego
        3. Validates signature version is supported
        4. Validates media type matches actual media
        5. Returns verification result with diagnostics
        
        Parameters:
        signature_dict (Dict[str, Any]):
            Deserialized signature dictionary.
        actual_media_type (str):
            Actual media type of the file being verified.
        payload_data (bytes, optional):
            Optional payload data to verify against signature.
            If provided, verifies that signature matches the payload.
            
        Returns:
        Dict[str, Any]: Verification result containing:
            - valid: Boolean indicating if signature is valid
            - platformName: Platform name from signature
            - platformVersion: Platform version from signature
            - mediaType: Media type from signature
            - signatureVersion: Signature version
            - createdAt: Creation timestamp
            - diagnostics: Detailed verification diagnostics
            
        Raises:
        MissingSignatureError: If signature is not present.
        InvalidSignatureError: If signature format is invalid.
        TamperedSignatureError: If HMAC verification fails.
        VersionMismatchError: If signature version is not supported.
        PlatformMismatchError: If platform identity does not match.
        MediaTypeMismatchError: If media type does not match.
        """
        start_time = time.time()
        diagnostics = {}
        
        try:
            logger.info("Starting platform signature verification")
            
            # Check if platform secret key is configured
            if not self.platform_secret_key:
                raise ValueError(
                    "PLATFORM_SECRET_KEY not configured. "
                    "Cannot verify platform signature."
                )
            
            # Extract signature fields
            platform_name = signature_dict[SIGNATURE_FIELD_PLATFORM]
            signature_version = signature_dict[SIGNATURE_FIELD_VERSION]
            signature_b64 = signature_dict[SIGNATURE_FIELD_SIGNATURE]
            created_at = signature_dict[SIGNATURE_FIELD_CREATED_AT]
            signature_media_type = signature_dict[SIGNATURE_FIELD_MEDIA_TYPE]
            
            # Build diagnostics
            diagnostics["platformName"] = platform_name
            diagnostics["platformVersion"] = signature_version
            diagnostics["mediaType"] = signature_media_type
            diagnostics["signaturePresent"] = True
            diagnostics["actualMediaType"] = actual_media_type
            
            # Step 1: Verify platform identity
            logger.info("Step 1: Verifying platform identity")
            if platform_name != self.platform_name:
                diagnostics["platformValid"] = False
                diagnostics["verificationStatus"] = "FAILED"
                diagnostics["verificationTime"] = round(time.time() - start_time, 3)
                raise PlatformMismatchError(
                    f"Expected platform '{self.platform_name}', "
                    f"got '{platform_name}'"
                )
            diagnostics["platformValid"] = True
            logger.info(f"Platform identity verified: {platform_name}")
            
            # Step 2: Verify signature version
            logger.info("Step 2: Verifying signature version")
            if signature_version not in self.supported_signature_versions:
                diagnostics["versionValid"] = False
                diagnostics["verificationStatus"] = "FAILED"
                diagnostics["verificationTime"] = round(time.time() - start_time, 3)
                raise VersionMismatchError(
                    f"Unsupported signature version: {signature_version}. "
                    f"Supported: {', '.join(self.supported_signature_versions)}"
                )
            diagnostics["versionValid"] = True
            logger.info(f"Signature version verified: {signature_version}")
            
            # Step 3: Verify media type
            logger.info("Step 3: Verifying media type")
            if signature_media_type != actual_media_type:
                diagnostics["mediaTypeValid"] = False
                diagnostics["verificationStatus"] = "FAILED"
                diagnostics["verificationTime"] = round(time.time() - start_time, 3)
                raise MediaTypeMismatchError(
                    f"Media type mismatch: signature says '{signature_media_type}', "
                    f"actual is '{actual_media_type}'"
                )
            diagnostics["mediaTypeValid"] = True
            logger.info(f"Media type verified: {signature_media_type}")
            
            # Step 4: Verify HMAC-SHA256
            logger.info("Step 4: Verifying HMAC-SHA256")
            
            # Reconstruct data that was signed
            data_to_verify = {
                "platform": platform_name,
                "version": self.platform_version,
                "mediaType": signature_media_type,
                "createdAt": created_at
            }
            
            # If payload data is provided, verify it matches
            if payload_data:
                payload_hash = hashlib.sha256(payload_data).hexdigest()
                data_to_verify["payloadHash"] = payload_hash
            
            # Convert to string (same order as generation)
            data_string = json.dumps(data_to_verify, separators=(',', ':'), sort_keys=True)
            
            # Generate HMAC for verification
            computed_signature_bytes = hmac.new(
                self.platform_secret_key.encode('utf-8'),
                data_string.encode('utf-8'),
                hashlib.sha256
            ).digest()
            
            # Decode signature from base64
            try:
                provided_signature_bytes = base64.b64decode(signature_b64)
            except Exception as e:
                diagnostics["hmacValid"] = False
                diagnostics["verificationStatus"] = "FAILED"
                diagnostics["verificationTime"] = round(time.time() - start_time, 3)
                raise InvalidSignatureError(f"Invalid base64 signature: {e}")
            
            # Compare HMACs using constant-time comparison
            hmac_valid = hmac.compare_digest(computed_signature_bytes, provided_signature_bytes)
            
            if not hmac_valid:
                diagnostics["hmacValid"] = False
                diagnostics["verificationStatus"] = "FAILED"
                diagnostics["verificationTime"] = round(time.time() - start_time, 3)
                raise TamperedSignatureError(
                    "HMAC verification failed. "
                    "Signature may have been tampered with."
                )
            
            diagnostics["hmacValid"] = True
            logger.info("HMAC-SHA256 verification passed")
            
            # Verification successful
            diagnostics["verificationStatus"] = "PASSED"
            diagnostics["verificationTime"] = round(time.time() - start_time, 3)
            
            result = {
                "valid": True,
                "platformName": platform_name,
                "platformVersion": signature_version,
                "mediaType": signature_media_type,
                "signatureVersion": signature_version,
                "createdAt": created_at,
                "diagnostics": diagnostics
            }
            
            logger.info(
                f"Platform signature verification passed in "
                f"{diagnostics['verificationTime']}s"
            )
            
            return result
            
        except (PlatformMismatchError, VersionMismatchError, 
                MediaTypeMismatchError, TamperedSignatureError) as e:
            # Re-raise specific verification errors
            logger.error(f"Signature verification failed: {e}")
            if e.details:
                logger.error(f"Details: {e.details}")
            raise
        except Exception as e:
            logger.error(f"Unexpected verification error: {e}")
            diagnostics["verificationStatus"] = "ERROR"
            diagnostics["verificationTime"] = round(time.time() - start_time, 3)
            raise InvalidSignatureError(f"Verification error: {e}")
    
    def verify_from_binary(
        self,
        signature_binary: bytes,
        actual_media_type: str,
        payload_data: bytes = None
    ) -> Dict[str, Any]:
        """
        Convenience method to deserialize and verify signature in one call.
        
        This method:
        1. Deserializes signature from binary
        2. Verifies signature using HMAC-SHA256
        3. Returns verification result with diagnostics
        
        Parameters:
        signature_binary (bytes):
            Binary signature data extracted from media.
        actual_media_type (str):
            Actual media type of the file being verified.
        payload_data (bytes, optional):
            Optional payload data to verify against signature.
            
        Returns:
        Dict[str, Any]: Verification result with diagnostics.
        """
        signature_dict = self.deserialize_signature(signature_binary)
        return self.verify_signature(signature_dict, actual_media_type, payload_data)
    
    def get_diagnostics_display(self, diagnostics: Dict[str, Any]) -> str:
        """
        Format diagnostics for display in debug panel.
        
        Parameters:
        diagnostics (Dict[str, Any]):
            Diagnostics dictionary from verify_signature.
            
        Returns:
        str: Formatted diagnostics string.
        """
        lines = [f"\n{DEBUG_SECTION_TITLE}", "=" * 50]
        
        for key, value in diagnostics.items():
            if isinstance(value, bool):
                value = "✓" if value else "✗"
            lines.append(f"{key}: {value}")
        
        return "\n".join(lines)


# Global signature validator instance
signature_validator = SignatureValidator()
