"""
Signature Constants Module for SecureStego Platform Verification

Purpose:
This module defines all constants used in the platform signature verification system.
Centralizing constants ensures consistency across the entire verification system.

Responsibilities:
- Define platform identification constants
- Define signature format constants
- Define supported media types
- Define version compatibility rules
- Define signature size limits

Workflow:
Constants are imported by other verification modules to ensure consistency.

Security Considerations:
- Version constants enable backward compatibility
- Media type constants prevent injection attacks
- Size limits prevent denial of service attacks
"""

from typing import List

# Platform Identification
PLATFORM_NAME = "SecureStego"
PLATFORM_VERSION = "1.0.0"
SIGNATURE_VERSION = "1.0"

# Supported Media Types
SUPPORTED_MEDIA_TYPES = [
    "image",
    "video",
    "audio",
    "document"
]

# Signature Format Constants
SIGNATURE_FIELD_PLATFORM = "platform"
SIGNATURE_FIELD_VERSION = "version"
SIGNATURE_FIELD_SIGNATURE = "signature"
SIGNATURE_FIELD_CREATED_AT = "createdAt"
SIGNATURE_FIELD_MEDIA_TYPE = "mediaType"

# Signature Size Limits (in bytes)
MAX_SIGNATURE_SIZE = 1024  # Maximum size for signature JSON
MIN_SIGNATURE_SIZE = 100   # Minimum size for signature JSON

# HMAC Configuration
HMAC_ALGORITHM = "SHA256"
HMAC_DIGEST_SIZE = 32  # 256 bits for SHA256

# Version Compatibility
SUPPORTED_SIGNATURE_VERSIONS = ["1.0"]

# Error Messages
ERROR_MISSING_SIGNATURE = "Platform signature not found in media"
ERROR_INVALID_SIGNATURE = "Invalid platform signature format"
ERROR_HMAC_VERIFICATION_FAILED = "HMAC verification failed - file may be tampered"
ERROR_PLATFORM_MISMATCH = "Platform identity mismatch - not generated by SecureStego"
ERROR_VERSION_MISMATCH = "Signature version not supported"
ERROR_MEDIA_TYPE_MISMATCH = "Media type mismatch in signature"

# Debug Labels
DEBUG_SECTION_TITLE = "Platform Verification Diagnostics"
