"""
Signature Exceptions Module for SecureStego Platform Verification

Purpose:
This module defines all custom exceptions used in the platform signature
verification system. Custom exceptions provide clear error handling and
meaningful error messages to the calling code.

Responsibilities:
- Define exception hierarchy for verification errors
- Provide clear error messages for different failure scenarios
- Enable graceful error handling in verification workflows
- Support debugging with detailed error information

Workflow:
Exceptions are raised when verification fails, allowing the calling code
to handle errors appropriately and provide meaningful feedback to users.

Security Considerations:
- Error messages do not expose sensitive information
- Exception hierarchy enables proper error handling
- Detailed errors logged but not exposed to frontend
"""


class SignatureVerificationError(Exception):
    """
    Base exception for all signature verification errors.
    
    Why this exists:
    - Provides a common base class for all verification exceptions
    - Enables catch-all error handling for verification failures
    - Ensures consistent error handling across the system
    
    Security Considerations:
    - Base exception does not expose sensitive details
    - Allows logging of full error context
    - Generic message returned to frontend
    """
    
    def __init__(self, message: str, details: str = None):
        """
        Initialize the signature verification error.
        
        Parameters:
        message (str):
            User-facing error message (safe to expose).
        details (str, optional):
            Detailed error information for logging (not exposed to frontend).
        """
        self.message = message
        self.details = details
        super().__init__(self.message)


class MissingSignatureError(SignatureVerificationError):
    """
    Raised when platform signature is not found in media.
    
    Why this exists:
    - Indicates the media was not generated by SecureStego
    - Distinguishes missing signature from invalid signature
    - Allows specific handling for unsigned media
    
    Security Considerations:
    - Indicates external tool was used
    - No sensitive information exposed
    - Logged for audit trail
    """
    
    def __init__(self, details: str = None):
        """
        Initialize missing signature error.
        
        Parameters:
        details (str, optional):
            Detailed error information for logging.
        """
        from app.verification.signature_constants import ERROR_MISSING_SIGNATURE
        super().__init__(ERROR_MISSING_SIGNATURE, details)


class InvalidSignatureError(SignatureVerificationError):
    """
    Raised when platform signature has invalid format.
    
    Why this exists:
    - Indicates signature structure is corrupted
    - Distinguishes format errors from cryptographic errors
    - Allows specific handling for malformed signatures
    
    Security Considerations:
    - May indicate tampering attempt
    - No sensitive information exposed
    - Logged for security monitoring
    """
    
    def __init__(self, details: str = None):
        """
        Initialize invalid signature error.
        
        Parameters:
        details (str, optional):
            Detailed error information for logging.
        """
        from app.verification.signature_constants import ERROR_INVALID_SIGNATURE
        super().__init__(ERROR_INVALID_SIGNATURE, details)


class TamperedSignatureError(SignatureVerificationError):
    """
    Raised when HMAC verification fails.
    
    Why this exists:
    - Indicates signature has been tampered with
    - Distinguishes cryptographic failures from format errors
    - Critical security indicator
    
    Security Considerations:
    - Indicates active tampering attempt
    - Logged as security event
    - Generic message returned to frontend
    """
    
    def __init__(self, details: str = None):
        """
        Initialize tampered signature error.
        
        Parameters:
        details (str, optional):
            Detailed error information for logging.
        """
        from app.verification.signature_constants import ERROR_HMAC_VERIFICATION_FAILED
        super().__init__(ERROR_HMAC_VERIFICATION_FAILED, details)


class VersionMismatchError(SignatureVerificationError):
    """
    Raised when signature version is not supported.
    
    Why this exists:
    - Indicates signature was created with incompatible version
    - Enables graceful handling of version upgrades
    - Allows migration strategies
    
    Security Considerations:
    - May indicate old or future version
    - No sensitive information exposed
    - Logged for compatibility tracking
    """
    
    def __init__(self, details: str = None):
        """
        Initialize version mismatch error.
        
        Parameters:
        details (str, optional):
            Detailed error information for logging.
        """
        from app.verification.signature_constants import ERROR_VERSION_MISMATCH
        super().__init__(ERROR_VERSION_MISMATCH, details)


class PlatformMismatchError(SignatureVerificationError):
    """
    Raised when platform identity does not match.
    
    Why this exists:
    - Indicates signature from different platform
    - Prevents cross-platform extraction
    - Critical for platform integrity
    
    Security Considerations:
    - Indicates external platform signature
    - Prevents unauthorized extraction
    - Logged as security event
    """
    
    def __init__(self, details: str = None):
        """
        Initialize platform mismatch error.
        
        Parameters:
        details (str, optional):
            Detailed error information for logging.
        """
        from app.verification.signature_constants import ERROR_PLATFORM_MISMATCH
        super().__init__(ERROR_PLATFORM_MISMATCH, details)


class MediaTypeMismatchError(SignatureVerificationError):
    """
    Raised when media type in signature does not match actual media.
    
    Why this exists:
    - Indicates signature was copied from different media type
    - Prevents signature replay attacks
    - Ensures media type integrity
    
    Security Considerations:
    - May indicate signature replay attack
    - Prevents cross-media extraction
    - Logged as security event
    """
    
    def __init__(self, details: str = None):
        """
        Initialize media type mismatch error.
        
        Parameters:
        details (str, optional):
            Detailed error information for logging.
        """
        from app.verification.signature_constants import ERROR_MEDIA_TYPE_MISMATCH
        super().__init__(ERROR_MEDIA_TYPE_MISMATCH, details)
